spring.application.name=reddit
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${db}
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.datasource.initialize=true
spring.jpa.show-sql=true

spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port = 2525
spring.mail.username=${username}
spring.mail.password =${password}
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true